name: Deploy Zola site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repo
      - uses: actions/checkout@v4

      # Step 2: Install Zola via the official action
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.2  # specify the version you want

      # Step 3: Build the site
      - run: zola build

      # Step 4: Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
